"""Stub file for badge.py"""
# ------------------- DO NOT EDIT ----------------------
# This file was generated by `scripts/pyi_generator.py`!
# ------------------------------------------------------

from typing import Optional, Union, overload
# from nextpy.components.libs.chakra import ChakraComponent
from nextpy.interfaces.web.components.component import Component
from nextpy.backend.vars import Var, BaseVar, ComputedVar
from nextpy.backend.event import EventHandler, EventChain, EventSpec

class ColorPicker(Component):
    @overload
    @classmethod
    def create(cls, *children, color,  **super().get_event_triggers(), on_change: lambda e0: [e0], **props ) -> "Color_Picker":
        """Create the component.

        Args:
            *children: The children of the component.
            variant: Variant of the badge ("solid" | "subtle" | "outline")
            color_scheme: The color of the badge
            **props: The props of the component.

        Returns:
            The component.

        Raises:
            TypeError: If an invalid child is passed.
        """
        ...