
import importlib
from typing import Any


def import_class(class_path):
    module_name, class_name = class_path.rsplit(".", 1)
    module = importlib.import_module(module_name)
    return getattr(module, class_name)

def document_loader(reader_type: str) -> Any:
    mapping = {
                "airtable": "openagent.rag.document_loaders.airtable.base.AirtableReader",
                "apify_dataset": "openagent.rag.document_loaders.apify.dataset.base.ApifyDataset",
                "asana": "openagent.rag.document_loaders.asana.base.AsanaReader",
                "azcognitive_search": "openagent.rag.document_loaders.azcognitive_search.base.AzCognitiveSearchReader",
                "bilibili": "openagent.rag.document_loaders.bilibili.base.BilibiliTranscriptReader",
                "boarddocs": "openagent.rag.document_loaders.boarddocs.base.BoardDocsReader",
                "chatgpt_plugin": "openagent.rag.document_loaders.chatgpt_plugin.base.ChatGPTRetrievalPluginReader",
                "chroma": "openagent.rag.document_loaders.chroma.base.ChromaReader",
                "confluence": "openagent.rag.document_loaders.confluence.base.ConfluenceReader",
                "couchdb": "openagent.rag.document_loaders.couchdb.base.SimpleCouchDBReader",
                "dad_jokes": "openagent.rag.document_loaders.dad_jokes.base.DadJokesReader",
                "deep_lake": "openagent.rag.document_loaders.deeplake.base.DeepLakeReader",
                "discord": "openagent.rag.document_loaders.discord.base.DiscordReader",
                "docugami": "openagent.rag.document_loaders.docugami.base.DocugamiReader",
                "elasticsearch": "openagent.rag.document_loaders.elasticsearch.base.ElasticsearchReader",
                "faiss": "openagent.rag.document_loaders.faiss.base.FaissReader",
                "feedly_rss": "openagent.rag.document_loaders.feedly_rss.base.FeedlyRssReader",
                "feishu_docs": "openagent.rag.document_loaders.feishu_docs.base.FeishuDocsReader",
                "file_directory": "openagent.rag.document_loaders.file.base.SimpleDirectoryReader",
                "file_audio": "openagent.rag.document_loaders.file.audio.base.AudioTranscriber",
                "gladia_audio": "openagent.rag.document_loaders.file.audio_gladia.base.GladiaAudioTranscriber",
                "file_cjk_pdf": "openagent.rag.document_loaders.file.cjk_pdf.base.CJKPDFReader",
                "deep_doctection": "openagent.rag.document_loaders.file.deepdoctection.base.DeepDoctectionReader",
                "file_docx": "openagent.rag.document_loaders.file.docx.base.DocxReader",
                "file_epub": "openagent.rag.document_loaders.file.epub.base.EpubReader",
                "flat_pdf": "openagent.rag.document_loaders.file.flat_pdf.base.FlatPdfReader",
                "image": "openagent.rag.document_loaders.file.image.base.ImageReader",
                "image_caption": "openagent.rag.document_loaders.file.image_blip.base.ImageCaptionReader",
                "image_vision": "openagent.rag.document_loaders.file.image_blip2.base.ImageVisionLLMReader",
                "image_tabular_chart": "openagent.rag.document_loaders.file.image_deplot.base.ImageTabularChartReader",
                "ipynb": "openagent.rag.document_loaders.file.ipynb.base.IPYNBReader",
                "json": "openagent.rag.document_loaders.file.json.base.JSONReader",
                "markdown": "openagent.rag.document_loaders.file.markdown.base.MarkdownReader",
                "mbox": "openagent.rag.document_loaders.file.mbox.base.MboxReader",
                "paged_csv": "openagent.rag.document_loaders.file.paged_csv.base.PagedCSVReader",
                "pandas_csv": "openagent.rag.document_loaders.file.pandas_csv.base.PandasCSVReader",
                "pandas_excel": "openagent.rag.document_loaders.file.pandas_excel.base.PandasExcelReader",
                "pdf": "openagent.rag.document_loaders.file.pdf.base.PDFReader",
                "pdf_miner": "openagent.rag.document_loaders.file.pdf_miner.base.PDFMinerReader",
                "pptx": "openagent.rag.document_loaders.file.pptx.base.PptxReader",
                "pymu_pdf": "openagent.rag.document_loaders.file.pymu_pdf.base.PyMuPDFReader",
                "rdf": "openagent.rag.document_loaders.file.rdf.base.RDFReader",
                "simple_csv": "openagent.rag.document_loaders.file.simple_csv.base.SimpleCSVReader",
                "unstructured": "openagent.rag.document_loaders.file.unstructured.base.UnstructuredReader",
                "firebase_realtimedb": "openagent.rag.document_loaders.firebase_realtimedb.base.FirebaseRealtimeDatabaseReader",
                "firestore": "openagent.rag.document_loaders.firestore.base.FirestoreReader",
                "github_repo_issues": "openagent.rag.document_loaders.github_repo_issues.base.GitHubRepositoryIssuesReader",
                "gmail": "openagent.rag.document_loaders.gmail.base.GmailReader",
                "google_calendar": "openagent.rag.document_loaders.google_calendar.base.GoogleCalendarReader",
                "google_docs": "openagent.rag.document_loaders.google_docs.base.GoogleDocsReader",
                "google_keep": "openagent.rag.document_loaders.google_keep.base.GoogleKeepReader",
                "google_sheets": "openagent.rag.document_loaders.google_sheets.base.GoogleSheetsReader",
                "gpt_repo": "openagent.rag.document_loaders.gpt_repo.base.GPTRepoReader",
                "graphdb_cypher": "openagent.rag.document_loaders.graphdb_cypher.base.GraphDBCypherReader",
                "graphql": "openagent.rag.document_loaders.graphql.base.GraphQLReader",
                "hatena_blog": "openagent.rag.document_loaders.hatena_blog.base.HatenaBlogReader",
                "hubspot": "openagent.rag.document_loaders.hubspot.base.HubspotReader",
                "huggingface_fs": "openagent.rag.document_loaders.huggingface.fs.base.HuggingFaceFSReader",
                "intercom": "openagent.rag.document_loaders.intercom.base.IntercomReader",
                "jira": "openagent.rag.document_loaders.jira.base.JiraReader",
                # "joplin": "openagent.rag.document_loaders.joplin.base.JoplinReader",
                "jsondata": "openagent.rag.document_loaders.jsondata.base.JSONDataReader",
                "kaltura_esearch": "openagent.rag.document_loaders.kaltura.esearch.base.KalturaESearchReader",
                "kibela": "openagent.rag.document_loaders.kibela.base.KibelaReader",
                # "make_com": "openagent.rag.document_loaders.make_com.base.MakeWrapper",
                "mangoapps_guides": "openagent.rag.document_loaders.mangoapps_guides.base.MangoppsGuidesReader",
                "maps": "openagent.rag.document_loaders.maps.base.OpenMap",
                "memos": "openagent.rag.document_loaders.memos.base.MemosReader",
                "metal": "openagent.rag.document_loaders.metal.base.MetalReader",
                "milvus": "openagent.rag.document_loaders.milvus.base.MilvusReader",
                "mondaydotcom": "openagent.rag.document_loaders.mondaydotcom.base.MondayReader",
                "mongo": "openagent.rag.document_loaders.mongo.base.SimpleMongoReader",
                "notion": "openagent.rag.document_loaders.notion.base.NotionPageReader",
                "obsidian": "openagent.rag.document_loaders.obsidian.base.ObsidianReader",
                "opendal": "openagent.rag.document_loaders.opendal_reader.base.OpendalReader",
                "opendal_azblob": "openagent.rag.document_loaders.opendal_reader.azblob.base.OpendalAzblobReader",
                "opendal_gcs": "openagent.rag.document_loaders.opendal_reader.gcs.base.OpendalGcsReader",
                "opendal_s3": "openagent.rag.document_loaders.opendal_reader.s3.base.OpendalS3Reader",
                "outlook_localcalendar": "openagent.rag.document_loaders.outlook_localcalendar.base.OutlookLocalCalendarReader",
                "pubmed": "openagent.rag.document_loaders.papers.pubmed.base.PubmedReader",
                "pinecone": "openagent.rag.document_loaders.pinecone.base.PineconeReader",
                "qdrant": "openagent.rag.document_loaders.qdrant.base.QdrantReader",
                "readwise": "openagent.rag.document_loaders.readwise.base.ReadwiseReader",
                "reddit": "openagent.rag.document_loaders.reddit.base.RedditReader",
                "slack": "openagent.rag.document_loaders.slack.base.SlackReader",
                "snscrape_twitter": "openagent.rag.document_loaders.snscrape_twitter.base.SnscrapeTwitterReader",
                "spotify": "openagent.rag.document_loaders.spotify.base.SpotifyReader",
                "stackoverflow": "openagent.rag.document_loaders.stackoverflow.base.StackoverflowReader",
                "steamship": "openagent.rag.document_loaders.steamship.base.SteamshipFileReader",
                "string_iterable": "openagent.rag.document_loaders.string_iterable.base.StringIterableReader",
                "trello": "openagent.rag.document_loaders.trello.base.TrelloReader",
                "twitter": "openagent.rag.document_loaders.twitter.base.TwitterTweetReader",
                "weather": "openagent.rag.document_loaders.weather.base.WeatherReader",
                "weaviate": "openagent.rag.document_loaders.weaviate.base.WeaviateReader",
                "async_web": "openagent.rag.document_loaders.web.async_web.base.AsyncWebPageReader",
                "beautiful_soup_web": "openagent.rag.document_loaders.web.beautiful_soup_web.base.BeautifulSoupWebReader",
                "knowledge_base_web": "openagent.rag.document_loaders.web.knowledge_base.base.RAGWebReader",
                # "readability_web": "openagent.rag.document_loaders.web.readability_web.base.ReadabilityWebPageReader",
                "rss": "openagent.rag.document_loaders.web.rss.base.RssReader",
                "simple_web": "openagent.rag.document_loaders.web.simple_web.base.SimpleWebPageReader",
                # "sitemap": "openagent.rag.document_loaders.web.sitemap.base.SitemapReader",
                "trafilatura_web": "openagent.rag.document_loaders.web.trafilatura_web.base.TrafilaturaWebReader",
                "unstructured_web": "openagent.rag.document_loaders.web.unstructured_web.base.UnstructuredURLLoader",
                "whatsapp": "openagent.rag.document_loaders.whatsapp.base.WhatsappChatLoader",
                "wikipedia": "openagent.rag.document_loaders.wikipedia.base.WikipediaReader",
                "wordlift": "openagent.rag.document_loaders.wordlift.base.WordLiftLoader",
                "wordpress": "openagent.rag.document_loaders.wordpress.base.WordpressReader",
                "youtube_transcript": "openagent.rag.document_loaders.youtube_transcript.base.YoutubeTranscriptReader",
                "zendesk": "openagent.rag.document_loaders.zendesk.base.ZendeskReader",
                "zulip": "openagent.rag.document_loaders.zulip.base.ZulipReader",
}
    reader_class = import_class(mapping[reader_type])
    return reader_class